# -*- coding: utf-8 -*-
"""KNN Dummy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11S2Cj6GYWP9WidOaTnPq4QTixnKUIhsQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("dummy_data_for_kmeans_discussion.xlsx")

plt.scatter(df.X,df.Y)
plt.title("Before Clustering")
plt.xlabel("X")
plt.ylabel("Y")

from sklearn.cluster import KMeans

km=KMeans(n_clusters=3)

km.fit(df)

ykm = km.predict(df)

plt.scatter(df.iloc[:,0],df.iloc[:,1],c=ykm)
plt.title("After Clustering")
plt.xlabel("X")
plt.ylabel("Y")

kv=KMeans(n_clusters=4)

a=[10355466,9797350,6343780,4724969,4360417,2864241,2582617,2534770,2445689,2443445,2279948,2032815,1627401,1593614]

df=pd.DataFrame({"A":a})
kv.fit(df)
ykv = kv.predict(df)
plt.scatter(df.iloc[:,0],df.iloc[:,0],c=ykv)
plt.title("After Clustering")

